# OPERATION CODES
FIND_SUCCESSOR = 0
UPDATE_FINGER_TABLE = 1
NOTIFY = 2
IS_ALIVE = 3

# IS_ALIVE_OPCODE = 0
# GET_PREDECESSOR_OPCODE = 1
# SET_PREDECESSOR_OPCODE = 2
# GET_SUCCESSOR_OPCODE = 3
# SET_SUCCCESSOR_OPCODE = 4
# FIND_SUCCCESSOR_OPCODE = 5
# UPDATE_FINGER_TABLE_OPCODE = 6
# STORE_OPCODE = 7
# GET_OPCODE = 8
# CLOSEST_PRECEDING_FINGER_OPCODE = 9
# NOTIFY_OPCODE = 10

# RESPONSES
OK_RESPONSE = 1
FAIL_RESPONSE = -1

